# preload = ~/.config/hypr/images/black-white.jpg
# wallpaper = eDP-1,contain:~/.config/hypr/images/black-white.jpg

wallpaper {
  monitor = eDP-1
  path = $HOME/.config/hypr/images/night.png
  fit_mode = cover
}
